Check that apps requested by `include "cluster.app.catalog"` are listed in the `Release`
giantswarm/cluster pull request #400
Opened 2024-12-06 13:16 UTC by AndiDog

### What does this PR do?

Fail chart deployment instead of deploying this if a (new) application isn't listed in `Release.spec.apps`:

```
sourceRef:
  kind: HelmRepository
  name: mycluster-
```

### What is the effect of this change to users?

Invalid `Release`s can't even be deployed 👍 

### How does it look like?

No change

### Any background context you can provide?

I came here from a failing E2E test whose base `Release` didn't have the new aws-node-termination-handler application, as expected ([comment](https://github.com/giantswarm/cluster-aws/pull/945#issuecomment-2523133158)). I'd rather have a hard error and easy-to-troubleshoot E2E test that searching for an empty string deep within the YAML jungle.

### Do the docs need to be updated?

No

### Should this change be mentioned in the release notes?

- [x] CHANGELOG.md has been updated (if it exists)

2024-12-07 19:48 UTC, Gacko requested changes

2024-12-07 19:48 UTC, Gacko commented on helm/cluster/templates/_helpers.tpl
> +{{- if $renderWithoutReleaseResource -}}
```suggestion
{{- else if $renderWithoutReleaseResource }}
```

2024-12-07 19:48 UTC, Gacko commented on helm/cluster/templates/_helpers.tpl
> +{{- end }}
```suggestion
```

2024-12-07 19:50 UTC, Gacko commented
Also since the commit message ends up in the history, I'd prefer a more descriptive one.

2024-12-12 17:11 UTC, AndiDog commented
> Also since the commit message ends up in the history, I'd prefer a more descriptive one.

I made more verb+action style – okay now?

2024-12-13 09:59 UTC, Gacko approved these changes

2024-12-13 12:36 UTC, Gacko commented
Can you put the changes on the GitHub action in a separate PR?

2024-12-13 15:22 UTC, AndiDog commented
> Can you put the changes on the GitHub action in a separate PR?

https://github.com/giantswarm/cluster/pull/405 – I shall rebase _this one_ once that's done

2024-12-13 15:23 UTC, AndiDog commented
We first need aws-nth-bundle listed in the latest `Release` before the draft PR tests can succeed

2024-12-14 12:02 UTC, Gacko approved these changes

2024-12-14 12:05 UTC, merged